name            'h0tbird-snmp'
version         '1.0.0'
source          'https://github.com/h0tbird/puppet'
author          'Marc Villacorta'
license         'GPL'
summary         'SNMP Module'
description     'SNMP Module'
project_page    'https://github.com/h0tbird/puppet'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
