name    'h0tbird-ntp'
version '0.0.1'
source 'https://github.com/h0tbird/puppet'
author 'Marc Villacorta'
license 'GPL'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
