name            'h0tbird-motd'
version         '0.0.1'
source          'https://github.com/h0tbird/puppet'
author          'Marc Villacorta'
license         'GPL'
summary         'Motd module'
description     'Motd module'
project_page    'https://github.com/h0tbird/puppet'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
